version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
        - order-management-network

  rabbitmq:
    image: rabbitmq:4.0-management
    restart: always
    container_name: rabbitmq
    hostname: docker-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/data
    networks:
      - order-management-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
    environment:
      - REDIS_PASSWORD=admin
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - order-management-network

networks:
  order-management-network:
    driver: bridge

volumes:
  postgres:
  rabbitmq:
  redis: