spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_management}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

order.validation.stock.queue=q.stock.validation
order.validation.discount.queue=q.discount.validation
order.validation.exchange=x.order.validation
order.validation.response.queue=q.validation.response
order.validation.response.exchange=x.validation.response
order.validation.response.wait.queue=q.validation.response.wait
order.validation.response.wait.exchange=x.validation.response.wait
order.rejected.queue=q.order.rejected
order.validation.response.dlx=dlx.validation.response
order.accounting.price.queue=q.accounting.price
order.accounting.price.exchange=x.accounting.price
order.payment.credit-card.queue=q.payment.credit-card
order.payment.wallet.queue=q.payment.wallet
order.payment.bank-transfer.queue=q.payment.bank-transfer
order.payment.exchange=x.payment
order.status.queue=q.order.status
order.status.exchange=x.order.status
order.status.key=order.status
